[workspace]
members = [
    "common",
    "canisters/router",
    "canisters/root",
    "canisters/sdk_example",
    "sdk/core",
    "sdk",
    "sdk/standards"
]

[profile.release]
lto = true
opt-level = 'z'
