[package]
name = "cap-sdk"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cap-core = { path = "core" }
ic-kit = "0.4"
futures = "0.3"